### ISSUE TITLE
 Questions about pre-training

### ISSUE THREAD

**Issue by rkfkfkfkr** [bakqui/ST-MEM#2]
Hello, I'd like to conduct pre-training on the st-mem model using the same dataset. I have all the datasets ready. My question pertains to the contents of st_mem/configs/pretraining.yaml. Could you please explain the components of the dataset section in pretraining.yaml? Specifically, could you describe how to generate ningbo_shaoxing_code15_10s.pkl?
![issue 질문](https://github.com/bakqui/ST-MEM/assets/103500394/0e6755ab-01c8-4a1b-a046-957c47f6dd0a)

**Comment by dduddus** [comment]
Hello, thank you for your interset in our works. The codes we uploaded in supplementary files focus on finetuning using the *PTB-XL* dataset. The whole training process(including data pre-processing) would be uploaded this repository soon.

**Comment by VaeReol** [comment]
hey, where do you get the code you provided above?

**Comment by LewisJeny** [comment]
hey, where do you get the code you provided above?

**Comment by dduddus** [comment]
Please refer to `./data/README.md` and `./data/process_ecg.py` for details. Then you can create your own dataset.
