### ISSUE TITLE
Questions on experiments

### ISSUE THREAD

**Issue by sehunfromdaegu** [bakqui/ST-MEM#3]
Thank you for the interesting work. 
1. I was just wondering how the authors could test the experiments with MTAE and MLAE because I cannot find their code. If somehow the authors have the code for MTAE, and MLAE, then do those models trained with the same dataset as yours?
2. Table 1 is the performance of arrhythmia and myocardial infarction (MI) classification tasks. In ptb-xl dataset, does this mean classification task using 5 superclasses?

Thank you in advance.

**Comment by dduddus** [comment]
Thank you for your interest.

1. We implemented MLAE and MTAE ourselves as there were no existing implementations available. Additionally, as mentioned in the paper, the pre-train dataset used is the same for the proposed method and all baseline methods.
2. That's right. 5 distct classes mean 5 super classes(CD, HYP, MI, NORM, STTC). For more information, check table 7.

**Comment by sehunfromdaegu** [comment]
Thank you for clear answer :)
