### ISSUE TITLE
Pretrained model selection

### ISSUE THREAD

**Issue by sehunfromdaegu** [bakqui/ST-MEM#5]
I'm excited to run the code, thanks for uploading.

1. I wonder how the pretrained model was selected for downstream task. Did you use the the pretrained model after 800 epochs? Or, pretrained model was selected among all epochs that work best for each downstream tasks?

2. Also, pretrained dataset code15 is not prepared in WFDB format, so I can't run /data/process_data.ecg.

3. How can I prepare a dataset for downstream task?

**Comment by sehunfromdaegu** [comment]
Since the downstream data preparation is not implemented, I have prepared ptb-xl, and used the transforms(random crop, highpass, lowpass filters) in this repository. 

However, the linear evaluation performance on ptb-xl multi-class (with the provided checkpoint) is very low compared to the reported performance. (I cannot obtain AUC > 0.7).

I suspect that the provided checkpoint does not produce high-quality representations. Is there a possibility that downstream performance is measured with different checkpoint?

**Comment by YunwonTae** [comment]
Thanks for your interest in this work!

1. We chose the final epoch.
2. You are correct. However, in “/data/process_data.ecg,” we only used WFDB for reading and loading the data. Therefore, I am confident that you can easily modify the code for other datasets.
3. After completing the processing step in “/data/process_data.ecg,” you will get an index.csv file where you can add the corresponding ECG labels provided by public datasets.
