### ISSUE TITLE
PTBXL dataset process

### ISSUE THREAD

**Issue by pengqianhan** [bakqui/ST-MEM#6]
Hello, thank you for sharing your code. It has been very helpful. I'm currently working on processing the PTB-XL dataset. While the process_ecg.py script functions correctly, the output doesn't quite meet my training requirements. As shown in the image, the LABEL column contains the filename rather than the actual ECG label. Could you provide additional code or guidance on how to properly process the PTB-XL dataset to include the correct labels? I would greatly appreciate your assistance. Thank you in advance
![Snipaste_2024-07-24_16-03-29](https://github.com/user-attachments/assets/06e3e726-58de-4960-b0f4-d196f02ec0d9)

**Comment by YunwonTae** [comment]
We appreciate your interest in this work!

We acknowledge that the index.csv file from “/data/process_data.ecg” only provides the processed signals without labels. However, we were confident that people could easily extend the label columns from public datasets, so we decided to release the general ECG processing clean code in this repository. The details about label processing are in our Appendix.

Thank you.
