### ISSUE TITLE
Question about reduced lead representation

### ISSUE THREAD

**Issue by kimsekeun** [bakqui/ST-MEM#7]
Dear author, 

if we have a one lead e.g. lead II, then what is the input for ST-MEM?
Zeros for other ECGs and only lead II fed to encoder? 
Could you explain how to embed one lead egg to ST-MEM?

Thanks.

**Comment by YunwonTae** [comment]
You don’t need any zero padding. You can simply embed a single-lead ECG into ST-MEM, which is the strength of this method.

**Comment by bakqui** [comment]
If you mean you would liked to obtain lead II model, you need to change both `model.num_leads` (`num_leads: 1`) and `dataset.lead` (`lead: lead2` or `lead: lead1`) of config YAML file.
Or if you would like to use the pre-trained 12-lead model for lead II ECG downstream task, just change `dataset.lead` only.
