### ISSUE TITLE
Question about t-SNE experiment

### ISSUE THREAD

**Issue by na-fi** [bakqui/ST-MEM#9]
Thanks for the intriguing work!

I have a question about the t-SNE experiment. For generating the embeddings, did you fine-tune on a downstream task, like classification, first? Or did you simply use the encoder with the pre-trained MAE weights?

Thank you

**Comment by YunwonTae** [comment]
Thank you for getting interested in our paper.

We used the pre-trained encoder weights and generated the embeddings. (didn't fine-tune on a downstream task)

**Comment by na-fi** [comment]
Thank you :)
